name: Create Release

on:
  pull_request:
  push:
    branches: [ "main" ] # FIXME: Remove after I'm done testing!
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: exrheader-rs-binary

jobs:
  build_and_upload_linux_x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
    - name: Build binary for ${{ runner.os }}-${{ runner.arch }}
      run: cargo build --release --verbose
    - name: Rename Binary
      run: |
        mkdir -p dist
        cp target/release/exrheader-rs dist/exrheader-rs-${{ runner.os }}-${{ runner.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BINARY_NAME }}-${{ github.sha }}-${{ env.BINARY_NAME }}-${{ runner.os }}-${{ runner.arch }}
        path: dist/exrheader-rs-${{ runner.os }}-${{ runner.arch }}

  # TODO: Once I have more time, revisit matrix workflows
  # and remove this duplication.
  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
  build_and_upload_macos_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
    - name: Build binary for ${{ runner.os }}-${{ runner.arch }}
      run: cargo build --release --verbose
    - name: Rename Binary
      run: |
        mkdir -p dist
        cp target/release/exrheader-rs dist/exrheader-rs-${{ runner.os }}-${{ runner.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BINARY_NAME }}-${{ github.sha }}-${{ runner.os }}-${{ runner.arch }}
        path: dist/exrheader-rs-${{ runner.os }}-${{ runner.arch }}

  release:
    needs:
      - build_and_upload_linux_x86
      - build_and_upload_macos_arm64

    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      # Fetch Linux x86 binary
      - name: Fetch binary artifact
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ env.BINARY_NAME }}-${{ github.sha }}-Linux-X64
          path: dist
          merge-multiple: true
      # Fetch macOS arm64 binary
      - name: Fetch binary artifact
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ env.BINARY_NAME }}-${{ github.sha }}-macOS-ARM64
          path: dist
          merge-multiple: true

      - name: Rename binaries to lowercase
        run: |
          for f in ./dist/*; do mv -v "$f" "$(echo $f | tr '[:upper:]' '[:lower:]')"; done

      # Create a new release
      # Docs: https://cli.github.com/manual/gh_release_create
      - name: Create GitHub Release
        run: |
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          gh release create $tag --generate-notes ./dist/* --fail-on-no-commits
